(function(){CTG.CARDS=CTG.CARDS||[];
function C(tool,f,b){CTG.CARDS.push({id:"c"+(CTG.CARDS.length+1),tool:tool,f:f,b:b});}
C("newthing","What stance does the book ask you to take toward its 'rules'?","There are no rules, only tools. Test each as a useful fiction; keep what works.");
C("newthing","Why does the book urge you to change your writing process?","Breaking habits (new place, new tool, new time) shakes loose fresh ideas and keeps you from autopilot.");
C("newthing","When should you do the book's exercises?","While the material is fresh, especially the awkward ones.");
C("truth_pain","Comedy = ?","Truth + pain.");
C("truth_pain","What is a joke's theme?","The truth and the pain it expresses.");
C("truth_pain","Why make truth and pain general rather than private?","General truths (the class clown) connect with many people; private ones (your own odd nerd experience) leave the audience out.");
C("truth_pain","First step when stuck on a situation?","State its truth and its pain before writing any joke.");
C("bogus","Two forms of bogus thinking?","False assumption ('it won't work') and faulty association ('they'll hate me').");
C("bogus","Who is the 'ferocious editor'?","The inner critic who kills ideas before they exist. Silence him while generating; invite him back for rewrites.");
C("bogus","Why are you judged less harshly than you fear?","Other people are too busy worrying about themselves.");
C("rule9","State the Rule of Nine.","For every ten ideas, nine will be trash, so make lots of ideas.");
C("rule9","Why set short time limits when listing?","Speed removes the sense that anything is at stake, quieting the editor.");
C("rule9","When do you judge the list?","After it's finished (or never).");
C("task_hand","Process or product: which does the book tell you to focus on?","Process. Concentrate on the task at hand: this word, this line.");
C("task_hand","What do you do when envy or fantasies of success intrude?","Return to the words on the page.");
C("pos_reinf","What is positive reinforcement in the book?","Applauding small victories: finish something small and explicitly take the win.");
C("pos_reinf","Order of judging your work?","Find something good first, then look at what's wrong.");
C("premise","Define a comic premise.","The gap between real reality and comic reality.");
C("premise","Why boil a premise to one line?","If you can't, you don't yet understand it.");
C("premise","Recipe for a premise?","Write what's expected (real reality), then insert the opposite or a skewed version (comic reality).");
C("conflict3","Name the three types of comic conflict.","Global (character vs world), local (character vs character), inner (character vs self).");
C("conflict3","Why pick a conflict type before brainstorming?","'What's funny?' is too vague; a narrowed question is easier to answer.");
C("conflict3","What do the best premises do with the three types?","Exploit all three levels at once.");
C("perspective","What is a comic perspective?","A character's single, strong, unusual way of seeing everything.");
C("perspective","How do you find a character's funny reaction?","Filter the event through their perspective.");
C("exaggeration","What does 'take it to the end of the line' mean?","Push the perspective to its ultimate extreme.");
C("exaggeration","Motto for exaggeration?","Too much is never enough. If you can't be right, be loud.");
C("exaggeration","Is it easier to pull back or push up?","Pull back from too much.");
C("flaws","A comic character is the ___ of his flaws.","Sum.");
C("flaws","What can a flaw be?","A virtue exaggerated (trusting becomes gullible).");
C("flaws","Why do generic characters fail?","No flaws means nothing separates them from 'real' people, so nothing is funny.");
C("humanity","What does humanity do for a comic character?","Bridges to the audience: positive qualities that make us care.");
C("humanity","Humanity rule of thumb?","For every flaw, an equal and opposite humanity; worse flaws need more.");
C("humanity","Danger of pasted-on humanity?","The character becomes a cartoon; it must be authentic to him.");
C("char_build","List the five slots of the character assembly line.","Name, perspective, flaws, humanity, exaggeration.");
C("char_build","What is the inner comic premise of a character?","Fantasy self-image versus reality.");
C("char_build","What do you look for among the slots?","Inner conflict: something always wrong when the rest is right.");
C("promise_title","What does every title do?","Makes a promise to the audience.");
C("promise_title","Titles workflow?","Brainstorm many titles, pick those whose promise excites you, then deliver (or knowingly twist) the promise.");
C("clash","Clash of context in one line?","Put a thing where it doesn't belong.");
C("clash","Question to ask for clash of context?","'Where would this never be?'");
C("clash","At what sizes does it work?","Word, line, scene or entire movie.");
C("inapp","Recipe for a wildly inappropriate response?","Situation, then the logical response, then its opposite or something wildly wrong.");
C("inapp","'Mildly' or 'wildly'?","Wildly. Exaggerate, rooted in the character's perspective.");
C("opposites","State the Law of Comic Opposites.","Lock two opposing comic perspectives together; each is the other's worst nightmare.");
C("opposites","Best question to generate opposites?","Who gives this person the worst possible time?");
C("tension","Joke = ?","Question (tension) + punchline (release).");
C("tension","How do you build tension?","Delay the payoff; milk the moment; dire circumstances store tension.");
C("payoff","Where does the funny word go?","Last.");
C("payoff","What do you do with words after the payoff?","Cut or move them.");
C("payoff","What must arrive before the payoff?","All setup information.");
C("truth_lie","Two ways to use honesty in comedy?","State the truth, or lie (the opposite or something wildly bigger), straight-faced.");
C("truth_lie","If truth doesn't work?","Try the lie, and vice versa.");
})();
