(function(){function C(tool,f,b){CTG.CARDS.push({id:"c"+(CTG.CARDS.length+1),tool:tool,f:f,b:b});}
C("sit_spec","How to choose a spec show?","A smart show you love that plays to your strengths; learn its rules first.");
C("sit_spec","Why does presentation matter?","Spelling and format are your calling card.");
C("sit_acts","Act break purpose?","A moment of maximum dread ('Oh no!') that keeps viewers across the commercial.");
C("sit_acts","Three-act breaks?","Trouble is coming; trouble is here.");
C("sit_stability","The arc of stability?","Old stability, instability, new stability.");
C("sit_stability","Why are sitcoms circular?","Audiences return for the same characters; change is subtle.");
C("sit_ab","A-story vs B-story?","A = main/heavy; B = smaller/lighter and thematically linked.");
C("sit_ab","How to state a theme?","As an imperative (Stand by your friends).");
C("sit_iccr","Four-sentence story shortcut?","Introduction, complication, consequence, relevance.");
C("sit_iccr","What is the implied fireworks scene?","The big scene the introduction promises; it tells you where to look for answers.");
C("sit_outline","Outline rule?","Detailed, present tense, rewritten repeatedly before any script.");
C("sit_outline","Plot logic and story logic?","Every move must satisfy both; avoid plot robots.");
C("sketch_setup","Sketch steps 1-3?","Strong comic character; force of opposition; forced union (set glue).");
C("sketch_setup","What is set glue?","The compelling reason the characters can't leave.");
C("sketch_esc","Sketch steps 4-9?","Escalate, raise stakes, push limits, emotional peak, find a winner, change the frame.");
C("sketch_esc","Why write a beat outline for sketches?","It's easier to fix structure in an outline than in a script.");
C("mining","Mining vs refining?","Separate jobs: generate, then edit. Do one at a time.");
C("mining","'Write long, cut hard' proportion?","Cut about 50%.");
C("hill","Hill-climbing problem?","You may have to come down the hill into fog to reach a taller mountain.");
C("hill","The myth of the last great idea?","The belief that your last good idea is your last. False.");
C("trust","How to validate your 'yes'?","Authenticate your 'no': earn trust through honest rejection.");
C("trust","Noodling?","Tinkering past diminishing returns; stop there.");
C("beta","Who makes a good beta tester?","A peer who can articulate specifics and be honest; not a buyer reading raw drafts.");
C("beta","Large vs small notes?","Large: structure, theme, story, character. Small: line-level.");
C("beta","How to take notes?","Listen, don't argue, adopt only what's useful.");
C("wince","Wince factor?","Read aloud, mark winces, fix them. Don't let yourself off the hook.");
C("fraud","Fraud police?","The inner voices saying you have no business doing this.");
C("fraud","How do you beat them?","Admit the fear out loud, ideally with humour (pre-emptive strike).");
C("charkeys","What is a character key?","One small vivid action that reveals the whole character.");
C("charkeys","Where do you put it?","At the character's first appearance.");
C("frames","Frames of reference?","What your audience knows and accepts.");
C("frames","Audience strategy?","Avoid the bland middle; connect with someone, even if it offends others; test widely.");
C("frames","Saddam Hussein effect?","A common enemy (e.g. a heckler) unifies the audience.");
C("vocab","Wade Boggs paradigm?","Even the best practise daily; so do you.");
C("vocab","Comic vocabulary daily target?","5 to 10 new jokes or jokoids; no structure worry.");
C("probsets","What is a problem set?","Define the parts that make a joke work, then solve for all parts.");
C("probsets","Pace of progress?","Leaplets, not leaps.");
C("drive","Success formula?","Talent + drive + time.");
C("drive","How to keep revelation alive?","Keep creating; train the weak tools.");
C("truth_pain","Example: truth and pain of a first date?","Truth: we all want to impress. Pain: fear of rejection / being found out.");
C("premise","Premise example?","'A man who is a pacifist is drafted': real reality is that soldiers fight; comic reality is that he won't.");
C("rule9","If only two of ten ideas are good, what does that mean?","You're beating the odds: nine in ten being trash is normal.");
C("exaggeration","Exaggerate a miser to the end of the line.","He charges his guests for reading his mail: the ultimate version of the perspective.");
C("flaws","Flaw pairs that fight a perspective?","A brave coward is funnier than a coward being only a coward; mix reinforcing and opposing flaws.");
C("humanity","Why does a monster need humanity?","So the audience can empathise; otherwise they won't care what happens.");
C("stakes","'Price of failure' example?","If he fails he loses the money, the house, and the one person who believes in him.");
C("mining","How to schedule writing sessions?","Separate sessions for mining and refining so they don't sabotage each other.");
C("task_hand","Task-at-hand prompt?","'What is the very next word?'");
C("fish","Fish out of water example?","A monk in Las Vegas.");
C("clash","Clash of context example?","A funeral held at a water park.");
C("doorbell","Doorbell example?","'Nobody knows we're here!' *knock*");
})();
