(function(){function C(tool,f,b){CTG.CARDS.push({id:"c"+(CTG.CARDS.length+1),tool:tool,f:f,b:b});}
C("center_ecc","What is 'center and eccentrics'?","One normal central character surrounded by about six comic characters, each with a strong perspective.");
C("center_ecc","What sustains an ensemble of eccentrics?","Lines of conflict between the characters.");
C("fish","Define fish out of water.","Put someone where they don't belong; the less they belong, the better.");
C("fish","Can the 'water' change be internal?","Yes (e.g. Big, Tootsie).");
C("fish","Which world should you choose?","The one that gives the hero the worst time.");
C("char_comedy","Character comedy formula?","Strong comic opposites at emotional war: forces pull them apart, equally strong forces hold them together.");
C("char_comedy","Classic pairing?","Haters who may become lovers.");
C("powers","Rule for magical-premise stories?","One simple, fascinating premise; keep the rules consistent.");
C("powers","Must the explanation be logical?","No: the explanation needn't make sense, the ride must.");
C("ensemble","What does a comic ensemble share?","A common goal or enemy, plus conflict within the group.");
C("ensemble","How to handle many characters?","Treat each as the hero of their own story and interleave.");
C("slapstick","Core of slapstick?","A character with no self-doubt: self-assurance versus manifest incompetence.");
C("slapstick","How to design slapstick?","Give delusions of grandeur, then torment them.");
C("satire_parody","Satire vs parody?","Satire attacks substance; parody attacks style.");
C("satire_parody","Safeguard for satire/parody?","Audience must know the target; add a real second-level story.");
C("tl_hero","Outer need vs inner need?","Outer = what the hero thinks he wants; inner = what he really wants.");
C("tl_hero","Default inner need if stuck?","Love, in the broad sense.");
C("tl_door","What is 'the door opens'?","The event that kicks the story into gear and thrusts the hero into a new, challenging world.");
C("tl_door","What is 'hero takes control'?","Early, surface-level success; the hero doesn't see what's coming.");
C("tl_door","One-sentence rule?","If a step can't be one sentence, you don't have it yet.");
C("tl_wrench","What's the monkey wrench?","A new bad thing, often a displaced loyalty (like love) that conflicts with the original goal.");
C("tl_wrench","What happens in 'things fall apart'?","Bad news piles up, ideally a trap of the hero's own making.");
C("tl_bottom","What is the moment of truth?","Choice between original loyalty and displaced loyalty, time running out.");
C("tl_bottom","What does 'risks all' look like?","Sacrificing everything for the displaced loyalty with no guarantee; often coming clean.");
C("tl_gets","Best ending in the throughline?","A double win: the hero serves both his original and displaced loyalties.");
C("tl_gets","How are the moment of truth and inner need related?","The moment of truth fulfils the inner need; know one and you know the other.");
C("rule3","Rule of three stages?","Introduction, validation, violation.");
C("rule3","Why two setups, not one or three?","One is not enough pattern; three is redundant and drains tension.");
C("rule3","What should the third item do?","Extravagantly not belong.");
C("jokoids","Define jokoid.","Something that looks and sounds like a joke but isn't one yet.");
C("jokoids","How do you repair a jokoid?","Change nouns, add detail, raise exaggeration, sharpen truth and pain.");
C("jokoids","Why write jokoids?","They free you to risk unfunny stuff; rewriting is easier than perfect first drafts.");
C("doorbell","What is the doorbell effect?","Create a strong expectation, then defeat it ruthlessly.");
C("doorbell","How to keep it fresh?","Misdirection; avoid the obvious version.");
C("cliches","Three ways to twist a cliche?","Phrase: swerve at the end. Situation: move it somewhere it doesn't belong. Character: give an inappropriate attitude.");
C("cliches","Why are cliches useful?","Each creates an expectation that you can defeat.");
C("running","Running gag rule?","Repeat but vary: change the detail, the stakes, the source, or let time change its meaning.");
C("running","Why do audiences love running gags?","The familiar 'buzz': you meet and then beat their expectation.");
C("callback","Callback definition?","Referring back to an earlier joke, often to button a scene.");
C("callback","Writing tip from callbacks?","Knowing the ending helps you write the beginning.");
C("stakes","Two ways to raise stakes?","Raise the price of failure; raise the prize for success.");
C("stakes","The question to ask instead of 'How can I make it funny?'","'What's at stake?'");
C("stakes","Hope and fear?","Let them coexist at the emotional core.");
C("dynamic","Story logic vs story dynamic?","Choose the boldest, most dynamic option even if it strains plausibility.");
C("dynamic","The target reaction?","'I can't believe that,' not 'I don't buy that.'");
C("micro","Micro vs macro conflict?","Macro = the big conflict; micro = small skirmishes that reflect it.");
C("micro","Order of working?","Find the macroconflict first, then list the echoing skirmishes.");
C("eartickle","What are ear tickles?","Alliteration, internal rhyme, puns: sound-play to polish a working joke.");
C("eartickle","Why distrust puns?","They have no emotional content (truth or pain).");
C("eartickle","When do you add them?","Last, and lightly.");
C("details","Details rule?","Specific beats generic: brand, year, texture, sound.");
C("details","Risk of details?","Distracting ones pull readers off the page. License to overdo, then trim.");
C("eyebrow","The eyebrow effect?","Each solution creates a slightly bigger problem than the last, until absurd.");
C("eyebrow","What kind of character feeds it?","A flawed one: scared, stubborn, stupid, desperate.");
C("virtual","Virtual humor = ?","A 3-D joke: tells story, truth and joke at once.");
C("virtual","How to rewrite a stuck moment?","State story, truth and humor in plain English, then rebuild in layers.");
C("allegiance","What builds audience allegiance?","Consistent rules, all the clues, meeting expectations.");
C("allegiance","Hope vs expectation?","Defeat hopes, not expectations; surprise inside the expected.");
})();
