(function(){
function E(tool,title,mode,min,target,instr,bank,tpl,o){o=o||{};CTG.EXERCISES.push({id:"e"+(CTG.EXERCISES.length+1),tool:tool,title:title,mode:mode,minutes:min,target:target,instr:instr,bank:bank||null,tpl:tpl||"",book:!!o.book,sprint:!!o.sprint,fields:o.fields||null,noedit:!!o.noedit});}
var F=function(a){return a.map(function(x){return {k:x[0],label:x[1],ph:x[2]||""}})};
E("promise_title","Title brainstorm","list",6,20,"Write twenty titles for a comedy built around the seed below. Then circle the one whose promise excites you (note it at the end).","people","Seed: {p}",{book:true,sprint:true,noedit:true});
E("promise_title","What does it promise?","rows",8,3,"For the title below, say what story it promises, who the hero is and what the premise should be.","title","Title: {p}",{fields:F([["promise","What it promises",""],["hero","The hero",""],["premise","The premise that delivers it",""]])});
E("clash","Clash of context: 20 pairs","list",6,20,"Write twenty 'X in Y' clashes using the thing and place below as a starting point, then continue with your own.",["thing","place"],"Start: {p} in {q}",{book:true,sprint:true,noedit:true});
E("clash","Clash into a scene","prose",8,80,"Take your favourite clash and write a short scene (80+ words) built on it.",["people","place"],"Try: {p} in {q}");
E("inapp","Wildly inappropriate responses","rows",8,3,"For the situation below, write the logical response, the opposite, and a wildly inappropriate response rooted in a character's perspective.","inapp","Situation: {p}",{book:true,fields:F([["logical","Logical response",""],["opposite","Opposite response",""],["wild","Wildly inappropriate response",""]])});
E("inapp","Inappropriate sprint","list",5,10,"Ten wildly inappropriate responses to the situation below, one per line.","inapp","Situation: {p}",{sprint:true,noedit:true});
E("opposites","Comic opposites: 5 pairs","rows",10,5,"For the character below, write an opposite and a place where they are locked together, with the first line of conflict.","opp","Character: {p}",{book:true,fields:F([["opp","The diametric opposite",""],["place","Forced together where? Why?",""],["conflict","First line of conflict",""],["worst","What makes it the worst time for each?",""],["title","Title",""]])});
E("opposites","Opposites list","list",5,12,"List twelve possible opposites for the character below, then star the best.","opp","Character: {p}",{sprint:true});
E("tension","Delay the payoff","prose",8,80,"Write a short setup (80+ words) that builds to a single punchline. Use delay, detail and pressure; the last word delivers the funny.","sit","Situation: {p}",{book:true});
E("tension","Tension builders","list",5,10,"Ten ways to add tension to the situation below before the punchline.","sit","Situation: {p}",{sprint:true});
E("payoff","Position the payoff: 12 jokes","list",8,12,"Write twelve one-sentence jokes about the topic below. For each, put the funniest word at the end.","thing","Topic: {p}",{book:true,sprint:true});
E("payoff","Reorder drill","rows",6,3,"Write a flat sentence about the topic below, then three versions that push the funniest word to the end.","thing","Topic: {p}",{fields:F([["flat","Flat sentence",""],["v1","Version 1",""],["v2","Version 2",""],["v3","Best payoff version",""]])});
E("truth_lie","Truth or lie?","rows",8,2,"For the situation below, write the honest line and the wildly false line. Pick the funnier.","truthsit","Situation: {p}",{book:true,fields:F([["truth","The truth said aloud",""],["lie","The lie (opposite or bigger)",""],["pick","Which is funnier and why?",""]])});
E("truth_lie","Truth sprint","list",5,10,"Ten blunt truths a character might say in the situation below, one per line.","truthsit","Situation: {p}",{sprint:true});
E("center_ecc","Center and eccentrics","rows",12,6,"Build a center and eccentrics cast in the setting below: one normal center and six eccentrics with a one-sentence comic perspective each, and the main lines of conflict.","setting","Setting: {p}",{book:true,fields:F([["center","The center",""],["e1","Eccentric 1",""],["e2","Eccentric 2",""],["e3","Eccentric 3",""],["e4","Eccentric 4",""],["e5","Eccentric 5",""],["e6","Eccentric 6",""],["lines","Lines of conflict",""]])});
E("fish","Fish-out-of-water pairings","list",6,12,"Pair the hero below with twelve worlds where they'd suffer most. Star the best.","fishhero","Hero: {p}",{book:true,sprint:true});
E("fish","Fish-out-of-water premise","rows",8,3,"Pair the hero and world below and write the premise, their worst day, and the first complication.",["fishhero","fishworld"],"Hero: {p} / World: {q}",{fields:F([["premise","Premise",""],["worst","Their worst day",""],["comp","First complication",""]])});
E("char_comedy","Character comedy pairs","rows",10,3,"Build two strong comic opposites and the forces that pull them apart and hold them together. Seed:","opp","Seed: {p}",{fields:F([["a","Character A (and perspective)",""],["b","Character B (and perspective)",""],["apart","Forces that pull them apart",""],["together","Forces that hold them together",""]])});
E("powers","Powers premise","rows",8,3,"Develop the magical premise below: the rule, its limit, three comic consequences, and one rule you must keep consistent.","power","Premise: {p}",{fields:F([["rule","The rule",""],["limit","The limit or cost",""],["cons","Three consequences",""],["consistent","What must stay consistent",""]])});
E("powers","Powers sprint","list",5,10,"Ten comic consequences of the power below.","power","Premise: {p}",{sprint:true});
E("ensemble","Ensemble blueprint","rows",12,5,"Build a comic ensemble for the group below: common goal or enemy, the conflicts inside the group, and each member's own story in one line.","group","Group: {p}",{fields:F([["goal","Common goal or enemy",""],["inner","Conflicts within the group",""],["m1","Member 1 and story",""],["m2","Member 2 and story",""],["m3","Member 3 and story",""]])});
E("slapstick","Slapstick: delusions and torment","rows",8,3,"Build a slapstick hero from the seed: what they believe about themselves, what's actually true, and three situations that torment them.","slap","Seed: {p}",{fields:F([["delusion","Delusion of grandeur",""],["truth","Manifest incompetence",""],["s1","Situation 1",""],["s2","Situation 2",""],["s3","Situation 3",""]])});
E("satire_parody","Satire or parody?","rows",10,4,"Pick the target below. Write one satire premise (attacks substance), one parody premise (attacks style), and a second-level story that would hold for those who miss the reference.","target","Target: {p}",{fields:F([["satire","Satire premise",""],["parody","Parody premise",""],["second","Second-level story",""],["audience","Does your audience know the target?",""]])});
})();
