(function(){
function E(tool,title,mode,min,target,instr,bank,tpl,o){o=o||{};CTG.EXERCISES.push({id:"e"+(CTG.EXERCISES.length+1),tool:tool,title:title,mode:mode,minutes:min,target:target,instr:instr,bank:bank||null,tpl:tpl||"",book:!!o.book,sprint:!!o.sprint,fields:o.fields||null,noedit:!!o.noedit});}
var F=function(a){return a.map(function(x){return {k:x[0],label:x[1],ph:x[2]||""}})};
E("tl_hero","Hero and needs","rows",8,3,"For the hero below, state the hero in one sentence, the outer need, and the inner need. Check they differ.","tlhero","Hero: {p}",{book:true,fields:F([["hero","Hero in one sentence",""],["outer","Outer need (thinks he wants)",""],["inner","Inner need (really wants)",""]])});
E("tl_door","Door opens and takes control","rows",8,2,"For the hero below, write the door-opens event and the hero-takes-control success. One sentence each.","tlhero","Hero: {p}",{fields:F([["door","The door opens",""],["control","The hero takes control",""]])});
E("tl_wrench","Monkey wrench","rows",8,3,"For the hero below, write a displaced loyalty (monkey wrench), the two mutually exclusive things he wants, and how things fall apart.","tlhero","Hero: {p}",{fields:F([["wrench","The monkey wrench (displaced loyalty)",""],["two","The two incompatible goals",""],["falls","How things fall apart",""]])});
E("tl_bottom","Moment of truth","rows",8,3,"For the hero below, write the bottom (the choice), what he risks, and how the inner need is fulfilled.","tlhero","Hero: {p}",{fields:F([["bottom","Hits bottom: the choice",""],["risk","Risks all: the sacrifice",""],["inner","The inner need it fulfils",""]])});
E("tl_gets","Full 10-step throughline","rows",20,10,"Write the complete 10-step throughline for the hero below, one sentence per step.","tlhero","Hero: {p}",{book:true,fields:F([["hero","1 Hero",""],["outer","2 Outer need",""],["inner","3 Inner need",""],["door","4 Door opens",""],["control","5 Takes control",""],["wrench","6 Monkey wrench",""],["falls","7 Things fall apart",""],["bottom","8 Hits bottom",""],["risk","9 Risks all",""],["gets","10 What he gets",""]])});
E("rule3","Rule of three: complete and invent","rows",8,5,"Complete each pattern with a wildly non-belonging third item. Then write five of your own from scratch (setup, setup, payoff).","r3","Start: {p}",{book:true,fields:F([["a","Joke 1",""],["b","Joke 2",""],["c","Joke 3",""],["d","Joke 4",""],["e","Joke 5",""]])});
E("rule3","Rule of three sprint","list",5,12,"Write twelve rule-of-three jokes. First two items establish the pattern; the third violates it.","r3","Seed: {p}",{sprint:true,noedit:true});
E("jokoids","Jokoids to jokes","list",8,15,"Write fifteen jokoids about the topic. Then circle two and rewrite them into real jokes.","jokoidtopic","Topic: {p}",{book:true,sprint:true,noedit:true});
E("jokoids","Repair a jokoid","rows",8,3,"Write a rough jokoid about the topic, state what's wrong with it, and repair it twice.","jokoidtopic","Topic: {p}",{fields:F([["joke","The jokoid",""],["wrong","What's wrong?",""],["fix1","Repair 1",""],["fix2","Repair 2",""]])});
E("doorbell","Doorbell effect: expectation defeated","rows",8,3,"For the strong expectation below, write three ways to defeat it. Prefer misdirection over the obvious.","expect","Expectation: {p}",{book:true,fields:F([["a","Defeat 1",""],["b","Defeat 2",""],["c","Defeat 3 (misdirection)",""]])});
E("doorbell","Doorbell sprint","list",5,10,"Ten ways to defeat the expectation below.","expect","Expectation: {p}",{sprint:true});
E("cliches","Twist a phrase","list",6,15,"Twist the cliche below at the end of the line. Write ten twists then five of your own.","cliche","Cliche: {p}",{book:true,sprint:true,noedit:true});
E("cliches","Twist a situation","rows",8,3,"Take a cliche situation and move it somewhere it doesn't belong. Also give the cliche character an inappropriate attitude.",["cliche_sit","cliche_char"],"Situation: {p} / Character: {q}",{fields:F([["sit","Moved situation",""],["char","Inappropriate attitude",""],["scene","A one-line scene",""]])});
E("running","Running gag: five variations","rows",10,5,"Take the gag seed and write five appearances that change the detail, the stakes, the source, or the meaning.","gag","Gag: {p}",{book:true,fields:F([["a","Appearance 1",""],["b","Appearance 2 (change detail)",""],["c","Appearance 3 (raise stakes)",""],["d","Appearance 4 (different source)",""],["e","Appearance 5 (time changes meaning)",""]])});
E("callback","Plant and callback","rows",8,3,"Write a scene opening with a planted line, a middle, and an ending that calls back to the planted line.","sit","Situation: {p}",{fields:F([["plant","Planted line",""],["middle","Middle",""],["callback","Callback to button the scene",""]])});
E("stakes","Price of failure: 30 consequences","list",8,30,"List thirty consequences of failure in the scene below, from small to enormous. Star the one that hits the emotional core.","stakes_scene","Scene: {p}",{book:true,noedit:true});
E("stakes","Prize for success","list",5,10,"Write ten things the character could win if they succeed, from small to enormous.","stakes_scene","Scene: {p}",{sprint:true});
E("dynamic","Bold or logical?","rows",8,3,"For the scene below, write the logical choice, the dynamic choice, and the boldest choice. Decide.","sit","Scene: {p}",{fields:F([["logical","Logical choice",""],["dynamic","Dynamic choice",""],["boldest","The boldest choice",""]])});
E("micro","Micro skirmishes","rows",10,5,"For the macroconflict below, write the macroconflict in one line and five skirmishes that reflect it.","macro","Macroconflict: {p}",{book:true,fields:F([["macro","Macroconflict in one line",""],["m1","Skirmish 1",""],["m2","Skirmish 2",""],["m3","Skirmish 3",""],["m4","Skirmish 4",""],["m5","Skirmish 5",""]])});
E("eartickle","Add ear tickles late","rows",8,3,"Write a working joke about the topic, then add alliteration or internal rhyme without breaking it.","thing","Topic: {p}",{fields:F([["joke","Joke that works",""],["tickle","With an ear tickle",""],["check","Did it get better or worse?",""]])});
E("details","Make it specific","rows",8,3,"Rewrite the plain sentence three times, adding specific details; then trim to the best.","plain","Sentence: {p}",{book:true,fields:F([["v1","Version 1 (specific)",""],["v2","Version 2 (more specific)",""],["best","Trimmed best",""]])});
E("details","Details list","list",5,15,"Fifteen specific details (brand, texture, sound, year) for the thing below.","thing","Thing: {p}",{sprint:true});
E("eyebrow","Eyebrow effect","rows",10,5,"Starting with the small problem below, write five steps where each fix creates a bigger problem.","eyeprob","Problem: {p}",{book:true,fields:F([["s1","Step 1",""],["s2","Step 2",""],["s3","Step 3",""],["s4","Step 4",""],["s5","Step 5 (absurd)",""]])});
E("virtual","3-D joke","rows",10,4,"For the scene below, write story, truth and humor in plain English, then a line that does all three.","virtualp","Scene: {p}",{fields:F([["story","The story",""],["truth","The truth",""],["humor","The humor",""],["line","A line that does all three",""]])});
E("allegiance","Consistent rules","rows",8,3,"For a premise, write three rules of your comic world and one way each could be broken that would betray the audience.","show","Premise: {p}",{fields:F([["r1","Rule 1 and betrayal",""],["r2","Rule 2 and betrayal",""],["r3","Rule 3 and betrayal",""]])});
})();
