(function(){
function E(tool,title,mode,min,target,instr,bank,tpl,o){o=o||{};CTG.EXERCISES.push({id:"e"+(CTG.EXERCISES.length+1),tool:tool,title:title,mode:mode,minutes:min,target:target,instr:instr,bank:bank||null,tpl:tpl||"",book:!!o.book,sprint:!!o.sprint,fields:o.fields||null,noedit:!!o.noedit});}
var F=function(a){return a.map(function(x){return {k:x[0],label:x[1],ph:x[2]||""}})};
E("sit_spec","Show rules sheet","rows",10,5,"Pick a show you know. Write its rules: characters and perspectives, a typical A/B story, what always happens, what never happens.","show","Practice with: {p}",{fields:F([["show","Show",""],["chars","Characters and perspectives",""],["always","What always happens",""],["never","What never happens",""],["story","One possible spec story",""]])});
E("sit_acts","Act breaks","rows",8,3,"For the show premise below, write three possible act breaks (moments of maximum dread).","show","Show: {p}",{fields:F([["a","Act break 1",""],["b","Act break 2",""],["c","Act break 3",""]])});
E("sit_stability","Arcs of stability","rows",10,6,"Generate arcs for the seed. Each as: old stability / instability / new stability, one sentence each. Write at least two arcs.","stability","Seed: {p}",{book:true,fields:F([["old","Arc 1 old stability",""],["inst","Arc 1 instability",""],["new","Arc 1 new stability",""],["old2","Arc 2 old stability",""],["inst2","Arc 2 instability",""],["new2","Arc 2 new stability",""]])});
E("sit_ab","A-story and B-story","rows",10,4,"For the show below, write an A-story, a B-story that comments on it, and the theme as an imperative.","show","Show: {p}",{fields:F([["a","A-story",""],["b","B-story",""],["theme","Theme (imperative)",""],["link","How B comments on A",""]])});
E("sit_iccr","4-sentence sitcom story","rows",8,4,"Write an introduction, complication, consequence and relevance for the show below, and name the implied fireworks scene.","show","Show: {p}",{book:true,fields:F([["i","Introduction",""],["c","Complication",""],["cc","Consequence",""],["r","Relevance",""],["fireworks","Implied fireworks scene",""]])});
E("sit_iccr","Story shortcut sprint","list",8,5,"Five complete 4-sentence story shortcuts for the seed. One line per story: I / C / C / R.","stability","Seed: {p}",{sprint:true});
E("sit_outline","Outline a sitcom","prose",20,200,"Write a present-tense outline (200+ words) of one episode for the show below. Check plot logic and story logic.","show","Show: {p}",{book:true});
E("sketch_setup","Sketch setup","rows",10,4,"Build steps 1-3 for the sketch seed: character, opposition and forced union.","sketchseed","Seed: {p}",{fields:F([["char","Strong comic character",""],["opp","Force of opposition",""],["glue","Set glue (forced union)",""],["first","The first moment of conflict",""]])});
E("sketch_esc","Nine-point sketch outline","rows",20,9,"Write a beat outline using all nine points for the sketch seed.","sketchseed","Seed: {p}",{book:true,fields:F([["1","1 Strong comic character",""],["2","2 Force of opposition",""],["3","3 Forced union",""],["4","4 Escalate",""],["5","5 Raise the stakes",""],["6","6 Push the limits",""],["7","7 Emotional peak",""],["8","8 Find a winner",""],["9","9 Change the frame",""]])});
E("mining","Write long, cut hard","prose",15,150,"Write 150+ words about the topic with no editing. Then cut about half and paste the survivors into your review notes.","sit","Topic: {p}",{book:true,noedit:true});
E("hill","Rewrite your best","rows",10,3,"Take your best joke or line from your journal, write it down, then rewrite it twice, willing to lose it.",null,"",{fields:F([["orig","The good version",""],["r1","Rewrite 1",""],["r2","Rewrite 2",""],["verdict","Which is best and why?",""]])});
E("trust","Authenticate your no","rows",8,3,"List three things you cut or rejected recently and why. Then say what that tells you about your judgment.",null,"",{fields:F([["a","Cut 1 and why",""],["b","Cut 2 and why",""],["c","Cut 3 and why",""],["learn","What it says about your judgment",""]])});
E("beta","Beta-test request","rows",6,3,"Write the instructions you would give a beta tester for a piece you made.",null,"",{fields:F([["who","Who and why",""],["ask","What you want to know (large and small notes)",""],["rules","How you'll respond to their notes",""]])});
E("wince","Wince hunt","prose",8,60,"Write a 60+ word scene with the situation below. Read it aloud, mark winces, and then note them in the review.","sit","Situation: {p}",{book:true});
E("fraud","Fraud police confession","rows",6,2,"Write what the fraud police say to you and then a funny pre-emptive confession you could say aloud.",null,"",{book:true,fields:F([["voice","What the fraud police say",""],["confess","Your pre-emptive confession",""]])});
E("charkeys","Character keys","list",6,10,"Write ten character keys: one small action per character that shows who they are.","charkeyc","Character: {p}",{book:true,sprint:true});
E("frames","Know your audience","rows",8,3,"For the topic and an imagined audience, list what they know, what they'll accept, and where the bland middle is.","frametopic","Topic: {p}",{fields:F([["audience","Audience",""],["know","What they know and accept",""],["bland","The bland middle to avoid",""],["bold","A bolder angle",""]])});
E("vocab","Comic vocabulary: 10 a day","list",8,10,"Add ten new funny things to your private file. They can be jokes, jokoids, observations, odd phrases. No structure needed.","thing","Seed (optional): {p}",{book:true,sprint:true,noedit:true});
E("probsets","Phobia problem set","rows",10,4,"Invent a phobia for the seed. Solve all parts: trivial fear, understandable, definition twists meaning, and a bonus ear tickle.","fear","Fear of: {p}",{book:true,fields:F([["name","Phobia name",""],["def","Definition (twist)",""],["trivial","Why it's trivial or absurd",""],["ear","Ear tickle",""]])});
E("probsets","Holic problem set","rows",8,3,"Invent a '-holic' term about the seed: a name, a one-line definition, and the comic truth behind it.","holic","Seed: {p}",{fields:F([["name","The word",""],["def","Definition",""],["truth","The truth behind it",""]])});
E("probsets","I hate to... problem set","list",6,15,"Complete the stem fifteen different ways, each with an unexpected, honest ending.","hate","Stem: {p}",{sprint:true,noedit:true});
E("drive","Talent + drive + time","rows",5,3,"Plan your next week of practice: three days, which tools and how long. Name the tool you most avoid.",null,"",{fields:F([["plan","Your practice plan",""],["avoid","The tool you avoid and why",""],["why","Why you want this",""]])});
})();
