(function(){
function P(n,s){CTG.PROMPTS[n]=s.split('|').map(function(x){return x.trim()}).filter(Boolean);}
P('inapp',"Your boss announces layoffs|A burglar breaks into your house|You're pulled over by the police|A baby is handed to you at a party|Your flight is cancelled|You win the lottery|Your date arrives with their ex|A fire alarm goes off|You find a spider in the shower|Your toast is burnt at a hotel breakfast|Someone steps on your foot|Your teacher catches you cheating|You're asked to give a eulogy|The waiter brings the wrong order|A stranger asks for directions|Your ATM eats your card|You're told you've been cut from the team|Your neighbour's dog digs up your garden|You learn your twin exists|The restaurant is out of everything on the menu|Your phone falls in the toilet|A mugger asks for your wallet|You walk in on your parents dancing|Your best friend forgets your birthday");
P('opp',"a neat freak|a slob|a pacifist|a drill sergeant|a hardened atheist|a fanatic believer|a chronic liar|a compulsive truth-teller|a night owl|a morning lark|a vegan|a competitive eater|a spendthrift|a miser|an introvert|a show-off|a pessimist|a perpetual optimist|a gossip|a vault of secrets|a control freak|a free spirit|a hypochondriac|a daredevil");
P('truthsit',"Meeting your ex at a wedding|Telling your boss his idea is bad|Being asked 'Does this look okay?'|Opening a gift you hate|Sitting through a bad school play|Complimenting a baby who looks like a potato|Meeting your partner's friends|Being told 'we need to talk'|A job interview question about your weaknesses|Leaving a party early|Reading your own old diary|Dieting after a holiday|Calling in sick|Being late to a meeting|Sending an email to the wrong person|Joining a gym in January|Hearing a friend's bad singing|Saying 'I'm fine'|Ordering at a fancy restaurant|Doing a group project");
P('setting',"a small-town diner|a hospital emergency room|a community theatre|a newspaper office|a barbershop|a hotel lobby|a high-school staff room|a radio station|a family-run funeral home|an airline check-in|a college dorm|a neighbourhood bar|a grocery store|a taxi dispatch office|a local TV news desk|a police precinct|a small-town church|a ranch|a tiny village post office|a cruise-ship kitchen");
P('fishhero',"a medieval knight|a Buddhist monk|a rural farmer|a top fashion model|a caveman|a Victorian governess|a pirate|a Martian|a retired sumo wrestler|a nun|a mafia boss|a goat herder|a high-powered lawyer|a sloth|a child prodigy|a ghost|an astronaut|a stage hypnotist|a king|a lumberjack");
P('fishworld',"a modern high school|Wall Street|a kindergarten|a hospital maternity ward|a romantic-comedy film set|a yoga retreat|a luxury hotel|a rock concert|a Parisian bakery|a garden club|a space-colony cafeteria|a wedding planner's office|a daytime talk show|a fast-food drive-thru|a ballet company|a dating app|a monastery|a supermarket|a pool party|a city council meeting");
P('power',"A man can read dogs' thoughts|A woman can't stop telling the truth|A teen can freeze time but only for 8 seconds|A boy's lies come true|A mother can hear everything said about her|A man swaps bodies with whoever he sneezes on|A girl's wishes are granted in the worst possible way|A man is followed by his own theme music|A woman ages backwards each Monday|A man can talk to appliances|A cat gets human speech|A teenager becomes invisible when embarrassed|A woman can see everyone's 'real' age|A man can't be lied to|A boy can make anyone laugh uncontrollably|A genie is bound to a cheapskate|A couple swap powers each night|A woman controls the weather with her mood|A man can taste emotions|A town where nobody can leave");
P('group',"the staff of a failing newspaper|passengers on a lifeboat|a jury locked in a room|a rock band on tour|a family reunion|a team of rookie astronauts|a group of retirees in a nursing home|a summer camp staff|neighbours in a condo board|a kitchen crew in a restaurant|a high-school debate team|survivors of a hotel fire|detectives in a small precinct|a gang of kidnappers|a bridal party|patients in group therapy|a village council|an amateur theatre cast|a hospital night shift|an expedition team");
P('slap',"a self-proclaimed genius|a world-class liar|a pompous opera singer|a would-be Casanova|a general with no army|an overconfident chef|a self-help guru|a daredevil with no skill|a king without a kingdom|a magician whose tricks fail|a runway model who can't walk|a sheriff afraid of guns|a detective who solves nothing|a motivational speaker who gives up|a bullfighter allergic to bulls|a stuntman afraid of heights");
P('target',"reality TV|self-help books|corporate retreats|political debates|luxury brands|wellness influencers|spy movies|talk shows|true-crime podcasts|startup culture|dating shows|cooking contests|fantasy epics|school bureaucracy|the airline industry|tech launches|home renovation shows|survival shows|royal weddings|motivational posters");
})();
