(function(){CTG.PROMPTS=CTG.PROMPTS||{};
function P(n,s){CTG.PROMPTS[n]=s.split('|').map(function(x){return x.trim()}).filter(Boolean);}
P('sit',"Waiting in line at the bank|Meeting your partner's parents|First day at a new job|Getting a haircut|A job interview|Parking in a crowded lot|A wedding toast|Moving to a new apartment|Going to the dentist|Returning an item without a receipt|A family dinner at the holidays|Being stuck in an elevator|Learning to drive|A first date|Airport security|Being a houseguest|Cooking for the boss|Giving a speech|Getting a speeding ticket|Standing in a crowded subway|A school reunion|Calling customer service|Buying a mattress|Assembling flat-pack furniture|A neighbourhood barbecue|Visiting a sick friend|Sitting an exam|Taking a long road trip with relatives|Asking for a raise|Moving back in with your parents");
P('thing',"a toaster|a garden gnome|a trombone|a wedding cake|a parking meter|a goldfish|a briefcase|a cactus|a bowling ball|a grandfather clock|an umbrella|a lighthouse|a tuxedo|a ladder|a vending machine|a fire extinguisher|a hammock|a snowman|a chandelier|a bicycle|a megaphone|a trophy|a telescope|a pogo stick|a shopping cart|a dentist's chair|a wedding ring|a typewriter|a piñata|a hot-air balloon");
P('people',"a retired general|a nervous magician|a pushy real-estate agent|a paranoid librarian|a lazy lifeguard|a competitive grandmother|a vegan butcher|a jealous mime|a lonely lighthouse keeper|an overconfident tour guide|a hypochondriac doctor|a shy auctioneer|a clumsy surgeon|a cheap millionaire|a stage mother|a hyperactive monk|a sulking clown|a timid bouncer|a know-it-all intern|a conspiracy-obsessed mailman|a perfectionist painter|a gossiping spy|a stingy fairy godmother|a nosy detective|a vain dentist|a bossy toddler|a sleepy air-traffic controller|a lying lie-detector expert|a cowardly firefighter|a talkative hermit");
P('place',"a funeral home|a casino|an airport lounge|a high-school gym|a monastery|a laundromat|a submarine|a used-car lot|a wedding reception|a library|a cruise ship|a nudist colony|a boardroom|a space station|a petting zoo|a hospital waiting room|a rodeo|a prison cafeteria|a ski lodge|a karaoke bar|a lighthouse|a tax office|a haunted house|a yoga studio|a roller rink|a department store|a mountain cabin|a courtroom|a police lineup|a bus depot");
P('perspective',"Everything is a competition|Everything is a conspiracy|Everything is dangerous|Everything is about money|Everything is a sign from God|Everything is an insult|Everything is a marketing opportunity|Everything is a performance|Everything is my fault|Everything is somebody else's fault|Everything is a romantic opportunity|Everything is a rule that must be enforced|Everything is a germ|Everything should be free|Everything is a test|Everything can be fixed with a plan|Everything was better in the past|Nothing is ever good enough|Everyone is secretly famous|Everyone is out to get me|Everything is an opportunity to teach|Everything is a tragedy|Everything is fine|Everything is a mystery to solve");
P('virtue',"trusting|confident|thrifty|loyal|helpful|honest|ambitious|careful|polite|optimistic|determined|creative|generous|patriotic|devout|punctual|brave|romantic|modest|tidy");
P('flawedchar',"a pushover boss|a gossip priest|a nervous cop|a mean nanny|a stage-frightened actor|an arrogant intern|a lazy inventor|a cheerful undertaker|a boastful beggar|a shy salesman|a tactless diplomat|a bitter bride|a forgetful spy|a selfish saint|a jealous best friend|a hot-tempered yoga teacher|a greedy charity worker|a naive con-man|a messy neat-freak|a loud librarian");
P('title',"Dead Man's Diet|The Nanny Cartel|Honey, I Hired the Neighbours|Sleepless in Sacramento|Bad Santa Fe|Mayor of Nowhere|Lunch Money|Dating Your Dentist|The Last Dinner Party|Overqualified|My Roommate the Wizard|Cousin Larry's Revenge|The Accidental Pope|How I Lost My Pension|Wedding Crashers Anonymous|Vegan Vampires|Mother Knows Worst|Twelve Angry Toddlers|Plumber to the Stars|Grand Theft Gnome|Honeymoon at Sea|Nine to Never|Raising Aunt Ruth|The Substitute Teacher's Revenge");
})();
