(function(){
function P(n,s){CTG.PROMPTS[n]=s.split('|').map(function(x){return x.trim()}).filter(Boolean);}
P('tlhero',"a timid accountant|a washed-up lounge singer|a rookie cop|a fussy hotel manager|a hopeless romantic baker|a failed inventor|a retired spy|a fake psychic|a stage dad|a small-town mayor|a ghostwriter|a cowardly knight|a phony doctor|a compulsive liar|a pushover teacher|a tone-deaf choirmaster|a lazy lifeguard|a nervous best man|a vain actor|a tightwad uncle");
P('r3',"Coffee, tea,|Faith, hope,|Red, white,|Ready, aim,|Wash, rinse,|Mom, Dad,|Breakfast, lunch,|Gold, silver,|Lights, camera,|Snap, crackle,|Reading, writing,|Sun, sand,|Shaken, stirred,|Rock, paper,|Larry, Moe,|Lawyer, doctor,|Past, present,|Hugs, kisses,|Stop, look,|Bonjour, hola,|Tall, dark,|Love, honour,|Eat, pray,|Hammer, nails,");
P('jokoidtopic',"airline food|going to the gym|online dating|working from home|children's birthday parties|IKEA|parallel parking|group chats|self-checkout|smart homes|office meetings|weddings|hotel minibars|moving house|diets|autocorrect|traffic jams|family WhatsApp groups|subscriptions|reality shows");
P('expect',"'Nobody will find us here.'|'This plan can't fail.'|'It'll be a quiet dinner.'|'Everything is under control.'|'It's just a harmless puppy.'|'The bridge is perfectly safe.'|'Just this once, nothing will go wrong.'|'No one is home.'|'It's an easy exam.'|'I'm sure he's asleep.'|'I'll only be a minute.'|'The surprise party is a total secret.'|'This is a nice, calm neighbourhood.'|'Don't worry, the doctor said it's routine.'|'The pilot sounds very confident.'|'We're fine as long as we stay quiet.'|'I would never cry at a wedding.'|'The parachute is brand new.'|'The speech will take two minutes.'|'The captain is a professional.'");
P('cliche',"Don't bite the hand that feeds you|Look before you leap|Better late than never|Every cloud has a silver lining|A penny saved is a penny earned|The early bird gets the worm|Actions speak louder than words|You can't judge a book by its cover|Don't count your chickens|The grass is always greener|Too many cooks spoil the broth|Time heals all wounds|Honesty is the best policy|Home is where the heart is|Out of sight, out of mind|Money doesn't grow on trees|All that glitters is not gold|Love is blind|Two wrongs don't make a right|When in Rome|Rome wasn't built in a day|A watched pot never boils|Practice makes perfect|The pen is mightier than the sword");
P('cliche_sit',"Cops interrogate a suspect|A man proposes on one knee|A couple fights at a restaurant|The hero defuses a bomb|A detective says 'You're off the case'|A teacher says 'See me after class'|A kidnapper demands a ransom|A mother-in-law arrives for a visit|A doctor says 'I have good news and bad news'|A car chase|The big game's final seconds|A courtroom confession|A 'Dear John' letter|A wedding objection scene|A deathbed confession|A pep talk in the locker room|A last-minute airport dash|A sudden power outage|A haunted house exploration|A bank robbery");
P('cliche_char',"the tough cop|the absent-minded professor|the nagging mother-in-law|the dumb blonde|the cowboy|the mad scientist|the grumpy old man|the damsel in distress|the ruthless CEO|the hardboiled detective|the kindly grandmother|the sensitive artist|the surfer dude|the nerdy sidekick|the drill sergeant|the gangster");
P('gag',"A man who always loses his keys|A neighbour who always interrupts|A dog that hates one person|A waiter who always forgets orders|A boss who mispronounces a name|A bumbling security guard|A character who keeps getting hit by something|A man who is always on a diet|A woman whose phone always rings at the worst time|A barista who gets every name wrong|A teacher who is always late|A man who keeps saying he's fine|A character who loves one terrible food|A friend who always shows up uninvited|A clock that is always wrong|A character who is always about to say something");
P('hate',"I hate to complain, but|I hate to brag, but|I hate to interrupt, but|I hate to say I told you so, but|I hate to be the one to tell you, but|I hate to bother you, but|I hate to sound paranoid, but|I hate to spoil the surprise, but|I hate to be negative, but|I hate to gossip, but|I hate to criticise, but|I hate to ask, but|I hate to rush you, but|I hate to disappoint you, but|I hate to burst your bubble, but");
P('stakes_scene',"A man tries to withdraw cash from an ATM|A woman tries to return a library book|A boy asks someone to the dance|A comic goes onstage|A man lies on his résumé|A couple hide a stolen gift|A teen sneaks out at night|A chef prepares a meal for a critic|A man tries to pass a driving test|A bride loses her ring|A cheapskate picks up a restaurant bill|A guest breaks a vase|A man hides a secret from his wife|A young lawyer's first case|A boy keeps a pet secret|A woman is late for the plane|A man must give a toast|A band plays their first gig|A man pretends to be a doctor|A student must tell a parent a grade");
P('macro',"Two brothers fight over an inheritance|A couple is splitting up|Two families merge|A company is being sold|A town is being bulldozed|A king is dying|Two rivals compete for the same job|A parent loses control of a teenager|A couple of newlyweds move in with in-laws|A school faces closure|A friend betrays a friend|A roommate is moving out|An old team is breaking up|A band wants a new singer|A chef sells the family restaurant|A parent is placed in a nursing home|A village debates a new road|Two siblings run a failing shop|A rancher defends his land|A boss is retiring");
})();
