(function(){
function P(n,s){CTG.PROMPTS[n]=s.split('|').map(function(x){return x.trim()}).filter(Boolean);}
P('plain',"A man walked into a restaurant and sat down.|A woman opened the door and saw her aunt.|The boy ate his breakfast.|The dog ran across the yard.|He drove to the office in his car.|She put on a coat and went outside.|The teacher gave back the tests.|He bought a drink at the bar.|The old man sat in his chair.|They had a big argument in the kitchen.|She wore a dress to the party.|He cooked dinner for his date.|The child played with a toy.|The doctor entered the room.|She felt nervous before the interview.|The comedian told a joke.|The waiter brought the bill.|He took a seat on the bus.|She heard a noise in the attic.|The cop wrote a ticket.");
P('eyeprob',"A man's tie is a little crooked|A cook's soup is slightly too salty|A woman's hair is a bit uneven|A burglar leaves his hat behind|A student has a typo in his essay|A man trims the hedge unevenly|A dad hangs a picture slightly crooked|A man puts a small stain on the carpet|A teen dents the family car|A chef burns the toast|A bride gets a tiny hole in her dress|A plumber leaks a drop|A waiter spills a little water|A man forgets his anniversary|A woman tells a small white lie|A boy breaks a window with a ball|A pilot takes a wrong turn|A bakery sells a slightly burnt cake|A painter misses a spot|A man sends an email to the wrong person");
P('virtualp',"A man tries to return a gift|A woman learns her date is her boss|A husband forgets his anniversary|A boy lies about his homework|A new employee gets lost|A father walks his daughter down the aisle|A cheapskate must tip|A man hides in a closet|A teacher fills in for a missing coach|Two friends compete over a trophy|A mother catches her teen sneaking in|A comic bombs at a wedding|A man gets his dream job and hates it|A couple adopts a dog|A neighbour borrows a lawn mower|A man gives a bad toast");
P('stability',"A bachelor lives alone and likes it|A mother controls her family's schedule|A grumpy boss runs a tight ship|A teen wants independence|Two roommates share chores equally|A couple lives in denial about money|A man hides his past|A grandmother rules the house|A young woman plans her wedding perfectly|A brother and sister never talk|A father forbids his daughter to date|A man refuses to retire|A town ignores its flood risk|A man lives off his parents|A friend group never says what they feel|A boss never praises|A husband won't ask directions|A couple pretends to be rich|A neighbour never lends anything|An uncle is always right");
P('show',"a sitcom about a failing family-run funeral home|a sitcom about two rival magicians who share an apartment|a sitcom about the staff of a small-town airline|a sitcom about a retired spy in a retirement village|a sitcom about a divorced couple who still share a house|a sitcom about a hospital's night-shift staff|a sitcom about a kindergarten teacher and her toughest parent|a sitcom about a failing local newspaper|a sitcom about a town's only bakery|a sitcom about a mountain rescue squad that never rescues anyone|a sitcom about a high-school principal who is afraid of students|a sitcom about a haunted house's tenants|a sitcom about a council-run zoo|a sitcom about an unsuccessful wedding planner|a sitcom about a rock band that is too old|a sitcom about a family-run cruise ship");
P('sketchseed',"A talk show where the host and guest are enemies|A dentist who is afraid of teeth|A job interview where the boss is the applicant|A restaurant where the waiter insults customers|A couple on a first date at a funeral|A game show with deadly consequences|A hostage negotiation over a parking ticket|A haunted house tour with a rude ghost|A family dinner where nobody can lie|A weatherman who can't predict the weather|A cooking show with a toddler judge|A wedding where the minister forgets the script|A bank robbery with polite robbers|A lifeguard who can't swim|A museum guide who knows nothing|A hostage in a library|A superhero support group|A sports commentator for a chess match|A refund counter for emotions|A jury that can't agree on lunch");
P('charkeyc',"an innocent grandmother|a jealous husband|a stingy uncle|an arrogant doctor|a coward cop|a naive intern|a perfectionist chef|a lazy lawyer|a flirtatious priest|a paranoid neighbour|a gossip teacher|a messy artist|a reckless driver|a social climber|a hypochondriac soldier|a vain king");
P('fear',"flip-flops|cheese|ceiling fans|escalators|unmatched socks|mirrors|rubber ducks|birthday cards|public restrooms|small talk|umbrellas|grocery lists|balloons|stairs|elevators|dust|sneezing|clocks|green traffic lights|buttons|pigeons|doorknobs|wet sand|mondays");
P('holic',"cheese|clocks|selfies|apologising|coupons|buses|nap time|weather reports|pencils|exclamation marks|hats|saving seats|ironing|spreadsheets|pillows|cleaning|raisins|scratch cards|reading terms and conditions|snow globes");
P('frametopic',"airline delays|work meetings|self-driving cars|dating apps|family holidays|smartphone addiction|school exams|politicians|supermarket self-checkout|wellness trends|reality TV|streaming subscriptions|cats vs dogs|office coffee|gym culture|gym memberships");
P('truth_list',"people lie on social media|nobody reads the terms|everyone's afraid of speaking in public|parents think their kids are geniuses|we all pretend to like our boss|nobody wants to be first on the dance floor|everyone pretends to know wine|nobody likes small talk|we all hate Monday|everyone tries to look busy|nobody admits they're lost|everyone believes they're a good driver|people say 'I'm fine' when they're not|we avoid eye contact in elevators|we all want a raise");
})();
